# batch
batch:
  enableDatasource: true
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbcUrl: jdbc:log4jdbc:h2:mem:apps;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    connectionTestQuery: select 1 from dual

# core
core:
  datasource:
    # default
    default:
      minimumIdle: 1
      maximumPoolSize: 4
    # readonly
#    readonly:
#      minimumIdle: 1
#      maximumPoolSize: 2


