#===============================================
# logging
#===============================================
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%-5level] %-32.32logger{32} : %m%n"
  level:
    root: DEBUG
    com.zaxxer.hikari: INFO
    org.apache.http.wire: INFO
    org.springframework.beans.factory.support.DefaultListableBeanFactory: INFO

#===============================================
# spring
#===============================================
spring:
  main:
    web-application-type: none
  output:
    ansi:
      enabled: DETECT

#===============================================
# batch
#===============================================
batch:
  enableDatasource: true
  datasource:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:apps;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    connectionTestQuery: select 1 from dual

#===============================================
# core
#===============================================
core:
  datasource:
    # default
    default:
      minimumIdle: 1
      maximumPoolSize: 4
    # readonly
#    readonly:
#      minimumIdle: 1
#      maximumPoolSize: 2


