# logging
logging:
  level:
    root: DEBUG
    org.apache.catalina.core.aprlifecyclelistener: INFO
    org.apache.tomcat.util.compat: INFO
    jdbc: OFF
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: DEBUG
    org.springframework: INFO
    com.zaxxer.hikari: INFO
    org.hibernate: INFO
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.basicbinder: TRACE

# spring
spring:
  main:
    web-application-type: none
  output:
    ansi:
      enabled: ALWAYS

# core
core:
  datasource:
    # default
    default:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:h2:mem:apps;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password:
      connectionTestQuery: select 1 from dual
    # readonly
    readonly:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:h2:mem:apps;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password:
      connectionTestQuery: select 1 from dual

