# logging
logging:
  level:
    root: debug
    org.apache.catalina.core.aprlifecyclelistener: info
    org.apache.tomcat.util.compat: info
    jdbc: off
    jdbc.sqltiming: debug
    jdbc.resultsettable: debug
    org.springframework: info
    com.zaxxer.hikari: info
    org.hibernate: info
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.basicbinder: trace

# spring
spring:
  profiles:
    default: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# core
core:
  datasource:
    # default
    default:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:h2:mem:apps;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password:
      connectionTestQuery: select 1 from dual
    # readonly
    readonly:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:h2:mem:apps;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password:
      connectionTestQuery: select 1 from dual
  initializeSchema: false
  dataSql: /db/data-h2.sql

