# logging
logging:
  level:
    root: DEBUG

# spring
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:apps;DB_CLOSE_ON_EXIT=FALSE;
      username: test
      password:
      connection-test-query: select 1 from dual
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


