# logging
logging:
  level:
    root: INFO
    org.apache.catalina.core.aprlifecyclelistener: INFO
    org.apache.tomcat.util.compat: INFO
    jdbc: OFF
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: DEBUG
    org.springframework: INFO
    com.zaxxer.hikari: INFO
    org.hibernate: INFO
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.basicbinder: TRACE

# spring
spring:
  main:
    web-application-type: none
  output:
    ansi:
      enabled: DETECT

# core
core:
  datasource:
    # default
    default:
      driverClassName: ~
      jdbcUrl: ~
      username: ~
      password: ~
      connectionTestQuery: ~
    # readonly
    readonly:
      driverClassName: ~
      jdbcUrl: ~
      username: ~
      password: ~
      connectionTestQuery: ~
