# logging
logging:
  level:
    root: DEBUG
    org.apache.coyote.http11: DEBUG

# server
server:
  port: 8080

# management
management:
  endpoints:
    web:
      exposure:
        include: '*'

# spring
spring:
  main:
    web-application-type: servlet
  mvc:
    static-path-pattern: /static/**
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  thymeleaf:
    enabled: true
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console

# springdoc
springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api
    groups-order: DESC
  group-configs:
    - group: version 1.0
      paths-to-match: /api/v1/**

# web
web:
  locales:
    - en_US
    - ko_KR
  secretKey: d8058b30f8208186d1d9cfa74c70ce31bd108b49aee773f7e4eb4e458a757c65
  defaultAuthorities:

