# logging
logging:
  level:
    root: DEBUG

# server
server:
  port: 8080

# management
management:
  endpoints:
    web:
      exposure:
        include: '*'

# spring
spring:
  main:
    web-application-type: servlet

# springdoc
springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api
    groups-order: DESC
  group-configs:
    - group: version 1.0
      paths-to-match: /api/v1/**


