apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-web 
spec:
  selector:
    matchLabels:
      app: apps-web 
  replicas: 2
  template:
    metadata:
      labels:
        app: apps-web
    spec:
      containers:
      - name: apps-web
        image: 192.168.0.2:9996/apps-web:dev 
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "local"
---
apiVersion: v1
kind: Service
metadata:
  name: apps-web
spec:
  type: LoadBalancer 
  selector:
    app: apps-web
  ports:
    - protocol: TCP
      port: 10000 
      targetPort: 8080

